### ISSUE TITLE
An error ocurred when fetching data

### ISSUE THREAD

**Issue by rshchpkn** [auth0-samples/auth0-ionic2-samples#8]
I have cloned this repo make npm install. Deploy on android device and it causes an error
 EXCEPTION: Error: An error ocurred when fetching data. main.js:42762
ORIGINAL STACKTRACE: main.js:42767
Error: Error: An error ocurred when fetching data.
    at file:///android_asset/www/build/main.js:2:6812
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14029)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:44:21430)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13965)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11389)
    at invoke (file:///android_asset/www/build/polyfills.js:3:15142) main.js:42768
Uncaught Error: Error: An error ocurred when fetching data.

**Comment by tairezzzz** [comment]
+1
